# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DjNcWTxcUk1qwhBqmA4uGcsVh_mhQR-8
"""

import os

# Crear la carpeta si no existe mediante código nativo de Python
os.makedirs("modulo2_hashing", exist_ok=True)

code_content = '''class ContactAgenda:
    def __init__(self):
        self.contacts_dict = {}

    def add_contact(self, name: str, phone_number: str) -> str:
        if name in self.contacts_dict:
            return f"Warning: Contact '{name}' already exists."
        self.contacts_dict[name] = phone_number
        return f"Contact '{name}' added successfully."

    def search_contact(self, name: str) -> str:
        phone_number = self.contacts_dict.get(name)
        if phone_number is not None:
            return f"Found! Phone number for {name}: {phone_number}"
        return f"Contact '{name}' not found."

    def update_contact(self, name: str, new_phone_number: str) -> str:
        if name in self.contacts_dict:
            self.contacts_dict[name] = new_phone_number
            return f"Contact '{name}' updated successfully."
        return f"Cannot update: Contact '{name}' does not exist."

    def delete_contact(self, name: str) -> str:
        if name in self.contacts_dict:
            del self.contacts_dict[name]
            return f"Contact '{name}' deleted successfully."
        return f"Cannot delete: Contact '{name}' does not exist."


if __name__ == "__main__":
    agenda = ContactAgenda()
    print(agenda.add_contact("Ana", "555-1234"))
    print(agenda.search_contact("Ana"))
    print(agenda.update_contact("Ana", "555-9999"))
    print(agenda.delete_contact("Ana"))
'''

with open("modulo2_hashing/agenda_diccionarios.py", "w", encoding="utf-8") as f:
    f.write(code_content)

test_content = '''import pytest
from agenda_diccionarios import ContactAgenda

def test_add_and_search_contact():
    agenda = ContactAgenda()
    agenda.add_contact("Ana", "555-1234")
    assert agenda.search_contact("Ana") == "Found! Phone number for Ana: 555-1234"

def test_search_non_existent_contact():
    agenda = ContactAgenda()
    assert agenda.search_contact("Carlos") == "Contact 'Carlos' not found."

def test_add_duplicate_contact():
    agenda = ContactAgenda()
    agenda.add_contact("Ana", "555-1234")
    res = agenda.add_contact("Ana", "555-0000")
    assert "already exists" in res
    assert agenda.search_contact("Ana") == "Found! Phone number for Ana: 555-1234"

def test_update_contact():
    agenda = ContactAgenda()
    agenda.add_contact("Ana", "555-1234")
    agenda.update_contact("Ana", "555-9999")
    assert agenda.search_contact("Ana") == "Found! Phone number for Ana: 555-9999"

def test_update_non_existent_contact():
    agenda = ContactAgenda()
    res = agenda.update_contact("Carlos", "555-0000")
    assert "does not exist" in res

def test_delete_contact():
    agenda = ContactAgenda()
    agenda.add_contact("Ana", "555-1234")
    agenda.delete_contact("Ana")
    assert agenda.search_contact("Ana") == "Contact 'Ana' not found."

def test_delete_non_existent_contact():
    agenda = ContactAgenda()
    res = agenda.delete_contact("Carlos")
    assert "does not exist" in res

def test_falsy_phone_number():
    agenda = ContactAgenda()
    agenda.add_contact("Zulema", "")
    assert agenda.search_contact("Zulema") == "Found! Phone number for Zulema: "
'''

with open("modulo2_hashing/test_agenda.py", "w", encoding="utf-8") as f:
    f.write(test_content)

readme_content = """# Module 2: Hash Table Implementation using Python Dictionaries

## Description
This project implements a contact agenda using Python's native `dict` data structure to demonstrate the efficiency of Hash Tables over linear and binary searches.

## Features (CRUD)
- **Create (`add_contact`)**: Inserts a new contact. Validates existence with `in` to prevent accidental overwrites.
- **Read (`search_contact`)**: Retrieves phone numbers using `.get()`, validating against `None` to handle empty strings or falsy values correctly.
- **Update (`update_contact`)**: Modifies an existing contact's phone number.
- **Delete (`delete_contact`)**: Removes a contact using the `del` keyword.

## Theoretical Justification: The 'Zulema' Case Study

### Scenario
An agenda containing **100 contacts ordered alphabetically**, searching for **"Zulema"** (located near or at the end of the list).

1. **Binary Search ($O(\\log n)$)**:
   - On an ordered list of $N = 100$ items, binary search recursively divides the search space in half.
   - Total operations: $\\lceil \\log_2(100) \\rceil \\approx 7$ comparison steps to locate "Zulema".

2. **Dictionary / Hash Table ($O(1)$)**:
   - The dictionary computes the hash value directly from the key `"Zulema"`.
   - Access time is constant ($O(1)$), completing the search in **1 single step** regardless of alphabetical order or size ($N$).

## Running Tests
To run the automated tests suite, execute:
`pytest modulo2_hashing/test_agenda.py`
"""

with open("modulo2_hashing/README.md", "w", encoding="utf-8") as f:
    f.write(readme_content)

print("¡README.md creado y guardado con éxito!")